# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
              # Pick your own package manager and build script
              env:
                  NUXT_PUBLIC_API_KEY: ${{ env.NUXT_PUBLIC_API_KEY }}
                  NUXT_PUBLIC_AUTH_DOMAIN: ${{ env.NUXT_PUBLIC_AUTH_DOMAIN }}
                  NUXT_PUBLIC_PROJECT_ID: ${{ env.NUXT_PUBLIC_PROJECT_ID }}
                  NUXT_PUBLIC_STORAGE_BUCKET: ${{ env.NUXT_PUBLIC_STORAGE_BUCKET }}
                  NUXT_PUBLIC_MESSAGING_SENDERID: ${{ env.NUXT_PUBLIC_MESSAGING_SENDERID }}
                  NUXT_PUBLIC_APP_ID: ${{ env.NUXT_PUBLIC_APP_ID }}
            - run: npm install
            - name: 'Create env file'
              run: |
                  touch .env
                  echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
                  echo API_KEY=${{ secrets.API_KEY }} >> .env
                  echo NUXT_PUBLIC_API_KEY=${{ env.NUXT_PUBLIC_API_KEY }} >> .env
                  echo NUXT_PUBLIC_AUTH_DOMAIN=${{ env.NUXT_PUBLIC_AUTH_DOMAIN }} >> .env
                  echo NUXT_PUBLIC_PROJECT_ID=${{ env.NUXT_PUBLIC_PROJECT_ID }} >> .env
                  echo NUXT_PUBLIC_STORAGE_BUCKET=${{ env.NUXT_PUBLIC_STORAGE_BUCKET }} >> .env
                  echo NUXT_PUBLIC_MESSAGING_SENDERID=${{ env.NUXT_PUBLIC_MESSAGING_SENDERID }} >> .env
                  echo NUXT_PUBLIC_APP_ID=${{ env.NUXT_PUBLIC_APP_ID }} >> .env
                  cat .env
            - run: npx nuxt build --preset github_pages --base="/svoyak/"
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./.output/public
    # Deployment job
    deploy:
        # Add a dependency to the build job
        needs: build
        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write # to deploy to Pages
            id-token: write # to verify the deployment originates from an appropriate source
        # Deploy to the github_pages environment
        environment:
            name: github_pages
            url: ${{ steps.deployment.outputs.page_url }}
        # Specify runner + deployment step
        runs-on: ubuntu-latest
        steps:
            - name: Deploy to GitHub Pages
              env:
                  NUXT_PUBLIC_API_KEY: ${{ env.NUXT_PUBLIC_API_KEY }}
                  NUXT_PUBLIC_AUTH_DOMAIN: ${{ env.NUXT_PUBLIC_AUTH_DOMAIN }}
                  NUXT_PUBLIC_PROJECT_ID: ${{ env.NUXT_PUBLIC_PROJECT_ID }}
                  NUXT_PUBLIC_STORAGE_BUCKET: ${{ env.NUXT_PUBLIC_STORAGE_BUCKET }}
                  NUXT_PUBLIC_MESSAGING_SENDERID: ${{ env.NUXT_PUBLIC_MESSAGING_SENDERID }}
                  NUXT_PUBLIC_APP_ID: ${{ env.NUXT_PUBLIC_APP_ID }}
              id: deployment
              uses: actions/deploy-pages@v4
